# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemon" do
  version "0.2.5"

  on_macos do
    on_intel do
      sha256 "2ed1ba3ef7f2268c5dc1cb9881dd2bb163150d76b30355ee645e42a0683cc362"
      url "https://github.com/mnemon-dev/mnemon/releases/download/v#{version}/mnemon_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0c9dae1a44f225b3963a5fdf5bee5a57e5ae98b13f72ebf6950287ce442541f6"
      url "https://github.com/mnemon-dev/mnemon/releases/download/v#{version}/mnemon_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9672488d0513922490dfef1a246920787e6d721d6f23b25a9e7f4f82c5231c55"
      url "https://github.com/mnemon-dev/mnemon/releases/download/v#{version}/mnemon_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9a028cf70d424f613bba23399413175fad85de6cf8d0c0f9f49da12a03760247"
      url "https://github.com/mnemon-dev/mnemon/releases/download/v#{version}/mnemon_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mnemon"
  desc "Persistent memory and durable agency for LLM agents"
  homepage "https://github.com/mnemon-dev/mnemon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnemon"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mnemon"]
    end
  end

  # No zap stanza required

end
