# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemon" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "30ab44520c81b8c04d4dff504b10e394154392cec454d3fafc5247fa74681177"
      url "https://github.com/mnemon-dev/mnemon/releases/download/v#{version}/mnemon_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0795c8bde653623f6fd07e8863001db2b88542ed98d9c6562eb0ddb8a4e64694"
      url "https://github.com/mnemon-dev/mnemon/releases/download/v#{version}/mnemon_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a04f9ad6dc671cd43eee829e59165fdfe9ffe2ff657b1011c1558a2515ebc29b"
      url "https://github.com/mnemon-dev/mnemon/releases/download/v#{version}/mnemon_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "89935930c9668613ef572f45dc9f026526d13ec0bb5c8a3ee5bf9bf25a54d442"
      url "https://github.com/mnemon-dev/mnemon/releases/download/v#{version}/mnemon_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mnemon"
  desc "Persistent memory and durable agency for LLM agents"
  homepage "https://github.com/mnemon-dev/mnemon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnemon"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mnemon"]
    end
  end

  # No zap stanza required

end
