# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemon" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "dd25daf163126e7493d38e27166ac744238a2d6c97fee65ec7ce45de23260317"
      url "https://github.com/mnemon-dev/mnemon/releases/download/v#{version}/mnemon_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "edec0278672f32b059c269ceb495bd1c2857bea44793229b9c781d28762fdd27"
      url "https://github.com/mnemon-dev/mnemon/releases/download/v#{version}/mnemon_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ca563ba87608454595808c3793b27faf53e6a7e5439fcc56acd0a4faf181fc04"
      url "https://github.com/mnemon-dev/mnemon/releases/download/v#{version}/mnemon_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ea619d25eb7da4aed6dce08c48f0ed738e3ca69ecd3a3563199b70bbddf2f3bc"
      url "https://github.com/mnemon-dev/mnemon/releases/download/v#{version}/mnemon_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mnemon"
  desc "Persistent memory and durable agency for LLM agents"
  homepage "https://github.com/mnemon-dev/mnemon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnemon"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mnemon"]
    end
  end

  # No zap stanza required

end
