# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mnemon < Formula
  desc "Persistent memory for LLM agents"
  homepage "https://github.com/mnemon-dev/mnemon"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mnemon-dev/mnemon/releases/download/v0.1.0/mnemon_0.1.0_darwin_amd64.tar.gz"
      sha256 "bd6c1a6533535a83350a094fa21fa13a0f0f215afc23c3f0aa4aefcac4f459ac"

      def install
        bin.install "mnemon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mnemon-dev/mnemon/releases/download/v0.1.0/mnemon_0.1.0_darwin_arm64.tar.gz"
      sha256 "cea280a093156bbbb70023791f460b03d1c924b0268fd7cf72e0eefb378fe160"

      def install
        bin.install "mnemon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mnemon-dev/mnemon/releases/download/v0.1.0/mnemon_0.1.0_linux_amd64.tar.gz"
      sha256 "28d283d3336cd2dac918c030dffa2e208750c4e9761759e79f3e2ce65fae669b"
      def install
        bin.install "mnemon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mnemon-dev/mnemon/releases/download/v0.1.0/mnemon_0.1.0_linux_arm64.tar.gz"
      sha256 "e15dd7868fd2c91282fe00febedeef7055a1ef3d52397511360271c3fb575075"
      def install
        bin.install "mnemon"
      end
    end
  end

  test do
    system "#{bin}/mnemon", "--version"
  end
end
