# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mnemon < Formula
  desc "Persistent memory for LLM agents"
  homepage "https://github.com/mnemon-dev/mnemon"
  version "0.1.13"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mnemon-dev/mnemon/releases/download/v0.1.13/mnemon_0.1.13_darwin_amd64.tar.gz"
      sha256 "34a9f0a65d134d3032d20664fdff77e8aa74c4b54659d7bc0f06c5ef5129b2bb"

      define_method(:install) do
        bin.install "mnemon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mnemon-dev/mnemon/releases/download/v0.1.13/mnemon_0.1.13_darwin_arm64.tar.gz"
      sha256 "0fedd3c07a7173c5b19af1718dfb4750f9aae436caaf5eacd39768049de1ed5c"

      define_method(:install) do
        bin.install "mnemon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mnemon-dev/mnemon/releases/download/v0.1.13/mnemon_0.1.13_linux_amd64.tar.gz"
      sha256 "75f5296fbbbbed5945ad1c21eb30aee13763cd59f649a2aa08761469b11947cb"
      define_method(:install) do
        bin.install "mnemon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mnemon-dev/mnemon/releases/download/v0.1.13/mnemon_0.1.13_linux_arm64.tar.gz"
      sha256 "a8a760fc691d05094d025202fba6ac402cc62a8d04502d8af2b7b1720bbee751"
      define_method(:install) do
        bin.install "mnemon"
      end
    end
  end

  test do
    system "#{bin}/mnemon", "--version"
  end
end
